export const ACTION = {
  AUTH: {
    INIT: 'AUTH_INIT',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGOUT: 'AUTH_LOGOUT',
  },
  USER: {
    GET_USER_START: 'GET_USER_START',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAIL: ' GET_USER_FAIL',
  },
};
